name: ColoredSigns
main: eu.mjezek.coloredsigns.ColoredSigns
version: 1.4
author: mjezek
description: Allows changing color of sign text with dye like in 1.14+.

permissions:
  coloredsigns.use:
    default: true
